::: {.content-visible when-profile="english"}
## Current position

-   Employee on LAUS project at the [Department of Botany, Faculty of Science, Charles University](https://natur.cuni.cz/en/biology/departments-and-work-places/department-of-botany)

-   Employee of [Institute of Botany of the Czech Academy of](https://www.ibot.cas.cz/en/) [Sciences](https://www.ibot.cas.cz/en/)

## Contact

-   jakubstenc at gmail.com

-   +420 774 553 734

## Education

-   2015-2018 - Bachelor's degree in biology, Faculty of Science, Charles university. Thesis: Pollination efficiency as a function of plant spatial aggregation and pollinator functional traits. Graduated.

-   2018-2020 - Master's degree in Botany, specialization Geobotany, Faculty of Science, Charles university. Thesis: Changes in pollinator behaviour under different plant spatial aggregation. Graduated with distinction.

-   2020-2024- Ph.D. in Botany, Faculty of Science, Charles university. Thesis: Factors influencing pollen carryover effectiveness. Graduated cuma sum laude.

## Work

-   2019 -- 2021 - Part-time employment as a technician at the Department of Botany, mainly managing the lab and reconstruction related activity, 0.1 FTE

-   2023 -- now - Employment on the INTER-ACTION-LUAUS23 project led by Petr Sklenář focusing on Pollination in tropical mountains, 0.5 FTE

-   2024 -- now - Employment on [Institute of Botany of the Czech Academy of](https://www.ibot.cas.cz/en/))[Sciences](https://www.ibot.cas.cz/en/)

Grant support 2018-2021 - Co-investigator of grant project from Grant Agency of Charles University: Plant population dynamics under anther smut epidemy and influence of pollinators on the rate of disease spread (1193619) 2019-2022 - Main investigator of grant project from Grant Agency of Charles University: Flower traits as drivers of pollinator visitation behaviour (842120) 2021-2023 -- Main investigator of grant project from Grant Agency of Charles University STAR: Do the plant pollen presentation schedules fit pollinator diurnal activity? A test of the Pollen Presentation Theory (0016935)

Educational stays abroad 2019 - 6-months Erasmus study abroad at University of Tartu (Estonia) 2022 - 2-months internship at Rey Juan Carlos University under supervision of Marcos Méndez 2023 - 1-month internship at University of Granada under supervision of Roccio Peréz Barrales

Conferences 2018 - SCAPE, The Scandinavian Association for Pollination Ecologists, Blessington, IRL (poster) 2019 - Kostelecké inspirování, CZU, CZE (oral presentation) 2019 - SCAPE, The Scandinavian Association for Pollination Ecologists, Höör, SWE (oral presentation) 2020 - EcoFlor conference, Bilbao, ESP (oral presentation) 2021 - EcoFlor online conference, Madrid ESP (organization and moderation of online discussion) 2022 - EcoFlor conference, Maó, ESP (oral presentation) 2022 - SCAPE, The Scandinavian Association for Pollination Ecologists, Warsaw, POL (oral presentation) 2023 - EcoFlor conference, Sevilla, ESP (oral presentation) 2024 - EcoFlor conference, Coimbra, POR (oral presentation)

Teaching experience R for life, Charles University in Prague, Czechia (2021, 2022; under leading of Martin Weiser and Tomáš Herben) Practical course on Plant Morphology, Charles University in Prague, Czechia (2020; under leading of Martin Čertner) Field course on Botany, Charles University in Prague, Czechia (2021; under leading of Jan Šťastný) Field course on Phytocenological and Plant-population Methods, Charles University in Prague, Czechia (2021; under leading of Tomáš Koubek)

Supervised students Alice Haveldová (Bachelors, supervision, finished) Karolína Chvojková (Bachelors, supervision, finished) Natálie Hanusová (Bachelors and Masters, supervision, ongoing) Petr Švanda (Bachelors and Masters, supervision, ongoing) Zuzana Matějková (Bachelor and Masters, co-supervision, ongoing) Lucie Holzbachová (Masters, co-supervision, ongoing)

Field experience nt position:

4\. year Ph.D. student, Dept. of Botany, Faculty of Science, CU.

Contact: jakubstenc\@gmail.com, +420 774 553 734

HEducation 2015-2018 - Bachelor's degree in biology, Faculty of Science, Charles university. Thesis: Pollination efficiency as a function of plant spatial aggregation and pollinator functional traits. Graduated. 2018-2020 - Master's degree in Botany, specialization Geobotany, Faculty of Science, Charles university. Thesis: Changes in pollinator behaviour under different plant spatial aggregation. Graduated with distinction. 2020-now - Ph.D. in Botany, Faculty of Science, Charles university. Thesis: Factors influencing pollen carryover effectiveness.

Work 2019 -- 2021 - Part-time employment as a technician at the Department of Botany, mainly managing the lab and reconstruction related activity, 0.1 FTE 2023 -- now - Employment on the INTER-ACTION-LUAUS23 project led by Petr Sklenář focusing on Pollination in tropical mountains

Grant support 2018-2021 - Co-investigator of grant project from Grant Agency of Charles University: Plant population dynamics under anther smut epidemy and influence of pollinators on the rate of disease spread (1193619) 2019-2022 - Main investigator of grant project from Grant Agency of Charles University: Flower traits as drivers of pollinator visitation behaviour (842120) 2021-2023 -- Main investigator of grant project from Grant Agency of Charles University STAR: Do the plant pollen presentation schedules fit pollinator diurnal activity? A test of the Pollen Presentation Theory (0016935)

Educational stays abroad 2019 - 6-months Erasmus study abroad at University of Tartu (Estonia) 2022 - 2-months internship at Rey Juan Carlos University under supervision of Marcos Méndez 2023 - 1-month internship at University of Granada under supervision of Roccio Peréz Barrales

Conferences 2018 - SCAPE, The Scandinavian Association for Pollination Ecologists, Blessington, IRL (poster) 2019 - Kostelecké inspirování, CZU, CZE (oral presentation) 2019 - SCAPE, The Scandinavian Association for Pollination Ecologists, Höör, SWE (oral presentation) 2020 - EcoFlor conference, Bilbao, ESP (oral presentation) 2021 - EcoFlor online conference, Madrid ESP (organization and moderation of online discussion) 2022 - EcoFlor conference, Maó, ESP (oral presentation) 2022 - SCAPE, The Scandinavian Association for Pollination Ecologists, Warsaw, POL (oral presentation) 2023 - EcoFlor conference, Sevilla, ESP (oral presentation) 2024 - EcoFlor conference, Coimbra, POR (oral presentation)

Teaching experience R for life, Charles University in Prague, Czechia (2021, 2022; under leading of Martin Weiser and Tomáš Herben) Practical course on Plant Morphology, Charles University in Prague, Czechia (2020; under leading of Martin Čertner) Field course on Botany, Charles University in Prague, Czechia (2021; under leading of Jan Šťastný) Field course on Phytocenological and Plant-population Methods, Charles University in Prague, Czechia (2021; under leading of Tomáš Koubek)

Supervised students Alice Haveldová (Bachelors, supervision, finished) Karolína Chvojková (Bachelors, supervision, finished) Natálie Hanusová (Bachelors and Masters, supervision, ongoing) Petr Švanda (Bachelors and Masters, supervision, ongoing) Zuzana Matějková (Bachelor and Masters, co-supervision, ongoing) Lucie Holzbachová (Masters, co-supervision, ongoing)

Field experience 2016-2017 -- field work with Insect communities' group (main researcher Robert Tropek) 2018-2020 -- field work experiments with Klará Koupilová and her project focused on plant pathogens transmitted by pollinators 2017-2023 -- field work for master and PhD thesis in Czech Republic 2023 -- 4 months of fieldwork in Andes, Ecuador

Languages and skills Czech (native), English (fluent), Spanish (advanced beginner) driving license A1 and B

Science popularization 2018 - 2020: guide in Botanical Garden of Faculty of Science, Charles University 2018 - 2024 -- Co-author of tasks for biological competition Biozvěst 2019 -- Co-author of exhibition "Intimní život rostlin" (The Intimate Life of Plants) in Botanical Garden of Prague (with Doc. RNDr. Lubomír Hrouda, CSc., RNDr. Zdeněk Janovský, Ph.D, RNDr. Jan Ponert PhD. and Mgr. Ludmila Němcová). 2020 -- Co-author of popular science article about anther smuts (Živa, not yet published)

Publications Janovský, Z., & Štenc, J. (2023). Pollinator community and generalisation of pollinator spectra changes with plant niche width and local dominance. Functional Ecology, 00, 1--10. https://doi.org/10.1111/1365-2435.14439

Matoušková, E., Štenc, J., & Janovský, Z. (2023). Innate preferences of Eristalis tenax L. (Syrphidae) for flower colour, size and symmetry are more intricate than the simple additive model. Biological Journal of the Linnean Society, 140(1), 110--119. https://doi.org/10.1093/BIOLINNEAN/BLAD035

Štenc, J., Janošík, L., Matoušková, E., Hadrava, J., Mikát, M., & Janovský, Z. (2023). Pollinator visitation closely tracks diurnal patterns in pollen release. American Journal of Botany, e16179. https://doi.org/10.1002/AJB2.16179

Koupilová, K., Štenc, J., & Janovský, Z. (2022). Pollinators adjust their behavior to presence of pollinator-transmitted pathogen in plant population. Behavioral Ecology, 33(2), 319--328. https://doi.org/10.1093/BEHECO/ARAB153

Koupilová, K., Štenc, J., & Janovský, Z. (2021). Pollen dispersal is driven by pollinator response to plant disease and plant spatial aggregation. Basic and Applied Ecology, 50, 77--86. https://doi.org/10.1016/j.baae.2020.10.0072016-2017 -- field work with Insect communities' group (main researcher Robert Tropek) 2018-2020 -- field work experiments with Klará Koupilová and her project focused on plant pathogens transmitted by pollinators 2017-2023 -- field work for master and PhD thesis in Czech Republic 2023 -- 4 months of fieldwork in Andes, Ecuador

Languages and skills Czech (native), English (fluent), Spanish (advanced beginner) driving license A1 and B

Science popularization 2018 - 2020: guide in Botanical Garden of Faculty of Science, Charles University 2018 - 2024 -- Co-author of tasks for biological competition Biozvěst 2019 -- Co-author of exhibition "Intimní život rostlin" (The Intimate Life of Plants) in Botanical Garden of Prague (with Doc. RNDr. Lubomír Hrouda, CSc., RNDr. Zdeněk Janovský, Ph.D, RNDr. Jan Ponert PhD. and Mgr. Ludmila Němcová). 2020 -- Co-author of popular science article about anther smuts (Živa, not yet published)

Publications Janovský, Z., & Štenc, J. (2023). Pollinator community and generalisation of pollinator spectra changes with plant niche width and local dominance. Functional Ecology, 00, 1--10. https://doi.org/10.1111/1365-2435.14439

Matoušková, E., Štenc, J., & Janovský, Z. (2023). Innate preferences of Eristalis tenax L. (Syrphidae) for flower colour, size and symmetry are more intricate than the simple additive model. Biological Journal of the Linnean Society, 140(1), 110--119. https://doi.org/10.1093/BIOLINNEAN/BLAD035

Štenc, J., Janošík, L., Matoušková, E., Hadrava, J., Mikát, M., & Janovský, Z. (2023). Pollinator visitation closely tracks diurnal patterns in pollen release. American Journal of Botany, e16179. https://doi.org/10.1002/AJB2.16179

Koupilová, K., Štenc, J., & Janovský, Z. (2022). Pollinators adjust their behavior to presence of pollinator-transmitted pathogen in plant population. Behavioral Ecology, 33(2), 319--328. https://doi.org/10.1093/BEHECO/ARAB153

Koupilová, K., Štenc, J., & Janovský, Z. (2021). Pollen dispersal is driven by pollinator response to plant disease and plant spatial aggregation. Basic and Applied Ecology, 50, 77--86. https://doi.org/10.1016/j.baae.2020.10.007
:::

::: {.content-visible when-profile="german"}
nada
:::
